### PR TITLE
fix player hang caused by script in some cases

### LINKED ISSUE #34: SubSelect seems to hang/crash MPV.
MPV Version: v0.38.0-743-gad7976c3
Script Version: Git Master
Platform: Windows 10 22H2

Both the issues described below go away when I remove the script from the scripts directory.

Video of the **first issue**: (If I'm playing any video and I close MPV, this is what happens, the MPV window hangs and then I have to kill the process via task manager.)

https://github.com/user-attachments/assets/c9dee0f2-06b8-49f3-84d7-f7fa99393aa4

Video of the **second issue**: (If I'm playing a video and I use my mpv keybind for playlist-next or playlist-prev the MPV window hangs as before.)

https://github.com/user-attachments/assets/f3030c4d-2084-4a8d-a3c3-92c26121a118

### PR DESCRIPTION
**Pull request by dyphire**
Close #34

### CODE REVIEW

**Comment by CogentRedTester** [comment]
The obvious solution would be to remove the `reset_track_ids()` function entirely and change `set_track()` to use the `file-local-options` version of the properties so that mpv resets the properties for us:

```lua
mp.set_property('file-local-options/'..type, id)
```

The question is why I didn't do that originally in #32? Did I have a reason or was I being an idiot? I'm not sure.

**Comment by dyphire** [comment]
> Do you know why the hook was causing freezes? I presumably used a hook here because the values needed to be reset before moving onto the next file, which would not be guaranteed by using the async end-file event. I suspect that this PR may break the behaviour intended by #32.

I'm not sure why the hook is causing the hang, except that I can reproduce it consistently on specific files, and after debugging it turns out that it's the script, the hook, that's causing it. It stands to reason that the new handling of event registration would not break the behaviour intended by #32.

> The obvious solution would be to remove the `reset_track_ids()` function entirely and change `set_track()` to use the `file-local-options` version of the properties so that mpv resets the properties for us:
> 
> ```lua
> mp.set_property('file-local-options/'..type, id)
> ```
> 
> The question is why I didn't do that originally in #32? Did I have a reason or was I being an idiot? I'm not sure.

This does look better, do I need to close this PR?

**Comment by CogentRedTester** [comment]
>  It stands to reason that the new handling of event registration would not break the behaviour intended by #32.

I disagree, the reason for the hook is that the aid and sid values need to be reset to 'auto' in order for subtitle selection in the next file to work. The values are queries during the on_preloaded hook, which means the values need to b be set to auto before this. The end-file event is asynchronous, the player keeps doing things while our event handler is running. This means there is no guarantee that the values will be reset before the preloaded hook. That's my assessment at least. 

> This does look better, do I need to close this PR?

You can if you like, but you're more than welcome to make that change in this PR.

**Comment by dyphire** [comment]
> > This does look better, do I need to close this PR?
> 
> You can if you like, but you're more than welcome to make that change in this PR.

Done.

**Pull request merged**
